name: lint test deploy
on:
    [push, workflow_dispatch]

jobs:
    lint:
        name: Run lint
        runs-on: ubuntu-latest
        steps:

        - name: checkout code
          uses: actions/checkout@v5.0.0

        - name: Setup Node.js environment
          uses: actions/setup-node@v5.0.0
          with:
            node-version: 18

        - name: Install dependencies
          run:  npm ci

        - name: Run Lint
          run: npm run lint        


    test:
        needs: lint
        name: Run Test
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v5.0.0
        
        - name: setup Node.js environment
          uses: actions/setup-node@v5.0.0
          with:
            node-version: 18

        - name: Install Dependencies
          run: npm ci

        - name: Run test
          run: npm test

    deploy:
        needs: test
        name: Deploy Code
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v5.0.0

        - name: Setup enviroment code
          uses: actions/setup-node@v5.0.0
          with:
            node-version: 18

        - name: Install dependencies
          run: npm ci

        - name: Build Project
          run: npm run build


        - name: Deploy code
          run: echo "Deploy Code"



